name: "refresh"

on:
  workflow_dispatch:
  schedule:
    - cron: '10 12 * * *'

jobs:
  aptb:
    uses: invalidunit/action/.github/workflows/aptb.yml@main
    with:
      _repo: https://flyx099.github.io/repo/


  remove_all_old_actions:
    uses: invalidunit/action/.github/workflows/remove_all_actions.yml@main
